package com.pdemuinck;

public enum ActivityEventType {
  ACTIVITY_JOINED,
  ACTIVITY_LEFT,
  ACTIVITY_PAUSED,
  ACTIVITY_OPEN,
  ACTIVITY_CLOSED,
  ACTIVITY_STARTED,
  ACTIVITY_FEEDBACK,
  ACTIVITY_NOT_ALLOWED
}
